In [6]:
from GameDummy import *

In [27]:
game = new_game(shuffle = False)

In [47]:
def move(game):
    actions = available_moves(game)
    for action in actions:
        print(action[-DACTION:])
        if action[DGAME:][HINT_NUMBER] != -1:
            print_game(
                hint_number(
                    action[:DGAME],
                    np.asscalar(action[DGAME:][PLAYER]),
                    np.asscalar(action[DGAME:][HINT_NUMBER]),
                )
            )
        if action[DGAME:][HINT_COLOR] != -1:
            print_game(
                hint_color(
                    action[:DGAME],
                    np.asscalar(action[DGAME:][PLAYER]),
                    np.asscalar(action[DGAME:][HINT_COLOR]),
                )
            )
        if action[DGAME:][PLAY] != -1:
            print_game(
                play(action[:DGAME], np.asscalar(action[DGAME:][PLAY]))
                )
        if action[DGAME:][DISCARD] != -1:
            print_game(discard(action[:DGAME], np.asscalar(action[DGAME:][DISCARD])))
        print("")

In [36]:
def print_game(game):
    print("LIFES ", game[LIFES])
    print("HINTS ", game[HINTS])
    print("DECK")
    print(game[DECK])
    print("DISCARDED")
    print(game[DISCARDED])
    for p in range(N_PLAYER):
        print("PLAYER ", p+1)
        for t in range(HAND_SIZE):
            print(game[PLAYERS][p*DPLAYER: (p+1)*DPLAYER][t*DHANDTILE:(t+1)*DHANDTILE])
    print("PILES ", game[PILES])

    


In [50]:
print(game)
print_game(game)

[-1  2  4  0  1  0  1  0  1  1  1  1  1  2  1 -1 -1 -1 -1 -1 -1 -1 -1 -1
 -1 -1 -1  0  0  0  0  0  0  1  0 -1 -1 -1 -1 -1  1  0 -1 -1 -1 -1 -1  2
  0 -1 -1 -1 -1 -1  0  0 -1 -1 -1 -1 -1  0  0 -1 -1 -1 -1 -1  0  0 -1 -1
 -1 -1 -1 -1 -1 -1]
LIFES  [2]
HINTS  [4]
DECK
[ 0  1  0  1  0  1  1  1  1  1  2  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
DISCARDED
[0 0 0 0 0 0]
PLAYER  1
[ 1  0 -1 -1 -1 -1 -1]
[ 1  0 -1 -1 -1 -1 -1]
[ 2  0 -1 -1 -1 -1 -1]
PLAYER  2
[ 0  0 -1 -1 -1 -1 -1]
[ 0  0 -1 -1 -1 -1 -1]
[ 0  0 -1 -1 -1 -1 -1]
PILES  [-1 -1]


In [51]:
move(game)

[-1 -1  0  1 -1 -1]
LIFES  [2]
HINTS  [3]
DECK
[ 0  1  0  1  0  1  1  1  1  1  2  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
DISCARDED
[0 0 0 0 0 0]
PLAYER  1
[ 1  0 -1 -1 -1 -1 -1]
[ 1  0 -1 -1 -1 -1 -1]
[ 2  0 -1 -1 -1 -1 -1]
PLAYER  2
[ 0  0  1 -1 -1 -1 -1]
[ 0  0  1 -1 -1 -1 -1]
[ 0  0  1 -1 -1 -1 -1]
PILES  [-1 -1]

[-1 -1  1  1 -1 -1]
LIFES  [2]
HINTS  [3]
DECK
[ 0  1  0  1  0  1  1  1  1  1  2  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
DISCARDED
[0 0 0 0 0 0]
PLAYER  1
[ 1  0 -1 -1 -1 -1 -1]
[ 1  0 -1 -1 -1 -1 -1]
[ 2  0 -1 -1 -1 -1 -1]
PLAYER  2
[ 0  0 -1  0 -1 -1 -1]
[ 0  0 -1  0 -1 -1 -1]
[ 0  0 -1  0 -1 -1 -1]
PILES  [-1 -1]

[-1 -1  2  1 -1 -1]
LIFES  [2]
HINTS  [3]
DECK
[ 0  1  0  1  0  1  1  1  1  1  2  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
DISCARDED
[0 0 0 0 0 0]
PLAYER  1
[ 1  0 -1 -1 -1 -1 -1]
[ 1  0 -1 -1 -1 -1 -1]
[ 2  0 -1 -1 -1 -1 -1]
PLAYER  2
[ 0  0 -1 -1  0 -1 -1]
[ 0  0 -1 -1  0 -1 -1]
[ 0  0 -1 -1  0 -1 -1]
PILES  [-1 -1]

[-1  0 -1  1 -1 -1]
LIFES  [2]
HINTS  [3]
D

In [49]:
game = next_turn(game)